---

- name: remove deprecated packages
  dnf:
    name: python-unversioned-command
    state: absent
  become: yes

- name: installing packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - nginx
    - vim
    - php
    - mariadb
    - unzip
    - curl
    - wget
    - bash-completion
    - policycoreutils-python-utils
    - mlocate
    - bzip2
    - cockpit-pcp
    - cockpit-bridge
    - cockpit-system
    - pcp
    - pcp-conf
    - pcp-selinux
    - pcp-libs
    - NetworkManager-tui
    - dnf-automatic
  become: yes
  notify:
    - start pmlogger
