---
# handlers file for SYSTEM

- name: start pmlogger
  ansible.builtin.service:
    name: pmlogger
    enabled: yes
    state: started
  become: yes

- name: restart virtual machine
  reboot:
  become: yes
